### ISSUE TITLE
cool tone isn't showing

### ISSUE THREAD

**Issue by aachar5** [aachar5/2ndassignment#2]
The  cool tones aren't showing in the plot. Though I used the cmap = 'coolwarm'

**Comment by Prukutu** [comment]
It looks like all the values in your map are beyond the high end of your colormap, giving you a single color all throughout. Please check the range of values in your data and adjust the clevs parameter accordingly. Alternately, you can see if the default selection of clevs works well for your plot by omitting that argument when you call `plt.contourf`.

**Comment by aachar5** [comment]
yes, it worked for me when I removed the clevs argument.

**Comment by Prukutu** [comment]
The colormap is now correctly showing the range of values that appears in your data. However, because you're omitting the clevs argument, the contour levels may get re-calculated at all time steps! The colorbar at the bottom will only reflect the values of the last time the contour levels were determined. You may want to manually set them for your plot after having checked them via the default selection so that we can be sure that the colorbar applies to all the subplots.
